package com.omega.ui.splitties

import android.graphics.Color


val THEME_COLOR_PRIMARY    by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#0288D1")}
val THEME_COLOR_SECONDARY  by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF4D79")}
val THEME_COLOR_ON_PRIMARY by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#ffffff")}
val THEME_COLOR_BACKGROUND by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#F2F2F2")}
val TEXT_COLOR_PRIMARY     by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF1A1A1A")}
val TEXT_COLOR_SECONDARY   by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#4D1A1A1A")}
val TEXT_COLOR_THIRDARY    by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#ffffff")}
val TEXT_COLOR_FOUR    by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#C9CACB")}
val COLOR_222222 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#222222")}
val COLOR_000000 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#000000")}
val COLOR_999999 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#999999")}
val COLOR_FD8099 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FD8099")}
val COLOR_FF85A7 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF85A7")}
val COLOR_0B0B0C by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#0B0B0C")}
val COLOR_B3B3B3 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#B3B3B3")}
val COLOR_BBBBBB by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#BBBBBB")}
val COLOR_444444 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#444444")}
val COLOR_FF3F8F by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF3F8F")}
val COLOR_FFF3F7 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFF3F7")}
val COLOR_1A1A1A by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#1A1A1A")}
val COLOR_661A1A1A by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#661a1a1a")}
val COLOR_FF5C00 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF5C00")}
val COLOR_1AEC843B by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#1AEC843B")}
val COLOR_26FFFFFF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#26FFFFFF")}
val COLOR_242424 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#242424")}
val COLOR_191919 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#191919")}
val COLOR_FF4D79 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF4D79")}
val COLOR_B3FFFFFF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#B3FFFFFF")}
val COLOR_F2F2F2 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#F2F2F2")}
val COLOR_CC1A1A1A by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#CC1A1A1A")}
val COLOR_F5F5F5 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#F5F5F5")}
val COLOR_FFFF4D79 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFFF4D79")}
val COLOR_1A000000 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#1a000000")}
val COLOR_1AFF843F by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#1aff843f")}
val COLOR_1AFFE00D by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#1affe00d")}
val COLOR_80FFE00D by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#80ffe00d")}
val COLOR_88000000 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#88000000")}
val COLOR_80000000 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#80000000")}
val COLOR_3F3830 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#3F3830")}
val COLOR_FF1A1A1A by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF1A1A1A")}
val COLOR_00000000 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#00000000")}
val COLOR_99000000 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#99000000")}
val COLOR_8A87FF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#8A87FF")}
val COLOR_ED85FF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#ED85FF")}
val COLOR_FF81DC by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF81DC")}
val COLOR_FFBF91 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFBF91")}
val COLOR_33000000 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#33000000")}
val COLOR_CCFFFFFF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#CCFFFFFF")}
val COLOR_01DF85 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#01DF85")}
val COLOR_B3000000 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#B3000000")}
val COLOR_303030 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#303030")}
val COLOR_FFB1B3B3 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFB1B3B3")}
val COLOR_FFEE2A7B by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFEE2A7B")}
val COLOR_FFFBFBFB by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFFBFBFB")}
val COLOR_FFF5F5F5 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFF5F5F5")}
val COLOR_FFE8E8E8 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFE8E8E8")}
val COLOR_FF0C0B0B by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF0C0B0B")}
val COLOR_FFF2F2F2 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFF2F2F2")}
val COLOR_4DFFFFFF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#4DFFFFFF")}
val COLOR_FFFFE00D by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFFFE00D")}
val COLOR_FF07B1EF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF07B1EF")}
val COLOR_F2FFFFFF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#f2ffffff")}
val COLOR_33FFFFFF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#33FFFFFF")}
val COLOR_FFFEFFDF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFFEFFDF")}
val COLOR_FFFFF4FE by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFFFF4FE")}
val COLOR_FFF789 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFF789")}
val COLOR_8763EC by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#8763EC")}
val COLOR_531E6A by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#531E6A")}
val COLOR_FFD9F4 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFD9F4")}
val COLOR_FBE0DA by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FBE0DA")}
val COLOR_E60B0B0C by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#E60B0B0C")}
val COLOR_336B7280 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#336B7280")}
val COLOR_6B7280 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#6B7280")}
val COLOR_FF0000 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF0000")}
val COLOR_FF6C6C by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF6C6C")}
val COLOR_FE2A2A by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FE2A2A")}
val COLOR_FF8E46 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF8E46")}
val COLOR_FFA962 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFA962")}
val COLOR_FFC47F by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFC47F")}
val COLOR_FFD692 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFD692")}
val COLOR_FFE3A0 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFE3A0")}
val COLOR_FFF3B1 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FFF3B1")}
val COLOR_FF782C by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FF782C")}
val COLOR_DE7C0C by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#DE7C0C")}
val COLOR_1AFFFFFF by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#1AFFFFFF")}
val COLOR_B1B3B3 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#B1B3B3")}
val COLOR_4C000000 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#4C000000")}
val COLOR_FBE041 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#FBE041")}
val COLOR_00000066 by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#66000000")}
val COLOR_CCFFE00D by lazy(LazyThreadSafetyMode.NONE) {Color.parseColor("#CCFFE00D")}
